export type DiscoveryShop = {
  id: string;
  name: string;
  categoryId: string;
  rating: number;
  distanceKm: number;
  etaMinutes: number;
  isOpenNow: boolean;
  isVerified: boolean;
  isTrending: boolean;
  createdAt: string;
  isPremium: boolean;
};

export const mockShops: DiscoveryShop[] = [
  {
    id: 'med-1',
    name: 'City Care Pharmacy',
    categoryId: 'medical',
    rating: 4.5,
    distanceKm: 1.2,
    etaMinutes: 20,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-11-02T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'med-2',
    name: 'Health Plus Store',
    categoryId: 'medical',
    rating: 4.4,
    distanceKm: 2.1,
    etaMinutes: 26,
    isOpenNow: true,
    isVerified: true,
    isTrending: false,
    createdAt: '2025-10-05T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'med-3',
    name: 'Apollo Generic Hub',
    categoryId: 'medical',
    rating: 4.3,
    distanceKm: 3.4,
    etaMinutes: 32,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-08-21T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'med-4',
    name: 'Pulse Medical Point',
    categoryId: 'medical',
    rating: 4.1,
    distanceKm: 5.5,
    etaMinutes: 42,
    isOpenNow: false,
    isVerified: false,
    isTrending: false,
    createdAt: '2025-06-13T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'med-5',
    name: 'Wellness Chemist',
    categoryId: 'medical',
    rating: 4.6,
    distanceKm: 1.8,
    etaMinutes: 24,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2026-01-10T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'gen-1',
    name: 'Daily Needs Mart',
    categoryId: 'general',
    rating: 4.6,
    distanceKm: 1.0,
    etaMinutes: 18,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-12-28T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'gen-2',
    name: 'Neighborhood Kirana',
    categoryId: 'general',
    rating: 4.2,
    distanceKm: 2.9,
    etaMinutes: 27,
    isOpenNow: true,
    isVerified: false,
    isTrending: false,
    createdAt: '2025-09-11T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'gen-3',
    name: 'Family Super Store',
    categoryId: 'general',
    rating: 4.1,
    distanceKm: 3.6,
    etaMinutes: 31,
    isOpenNow: true,
    isVerified: true,
    isTrending: false,
    createdAt: '2025-07-20T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'gen-4',
    name: 'Smart Basket Hub',
    categoryId: 'general',
    rating: 4.4,
    distanceKm: 0.9,
    etaMinutes: 16,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2026-02-08T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'gen-5',
    name: 'Everyday Value Store',
    categoryId: 'general',
    rating: 4.0,
    distanceKm: 6.7,
    etaMinutes: 45,
    isOpenNow: false,
    isVerified: false,
    isTrending: false,
    createdAt: '2025-05-02T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'clo-1',
    name: 'Fashion Lane',
    categoryId: 'clothes',
    rating: 4.0,
    distanceKm: 2.6,
    etaMinutes: 28,
    isOpenNow: true,
    isVerified: true,
    isTrending: false,
    createdAt: '2025-10-18T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'clo-2',
    name: 'Urban Wear Point',
    categoryId: 'clothes',
    rating: 4.3,
    distanceKm: 4.1,
    etaMinutes: 35,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-11-25T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'clo-3',
    name: 'Classic Outfit House',
    categoryId: 'clothes',
    rating: 4.1,
    distanceKm: 5.2,
    etaMinutes: 39,
    isOpenNow: false,
    isVerified: true,
    isTrending: false,
    createdAt: '2025-08-08T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'clo-4',
    name: 'Ethnic Avenue',
    categoryId: 'clothes',
    rating: 4.5,
    distanceKm: 1.5,
    etaMinutes: 23,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2026-01-30T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'clo-5',
    name: 'Street Style Spot',
    categoryId: 'clothes',
    rating: 3.9,
    distanceKm: 7.4,
    etaMinutes: 47,
    isOpenNow: false,
    isVerified: false,
    isTrending: false,
    createdAt: '2025-04-27T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'bak-1',
    name: 'Bake Fresh Corner',
    categoryId: 'bakery',
    rating: 4.4,
    distanceKm: 1.7,
    etaMinutes: 21,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-12-15T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'bak-2',
    name: 'Sweet Oven House',
    categoryId: 'bakery',
    rating: 4.2,
    distanceKm: 2.3,
    etaMinutes: 25,
    isOpenNow: true,
    isVerified: true,
    isTrending: false,
    createdAt: '2025-09-05T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'fru-1',
    name: 'Green Basket Fruits',
    categoryId: 'fruits',
    rating: 4.3,
    distanceKm: 0.8,
    etaMinutes: 17,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2026-02-17T09:00:00.000Z',
    isPremium: true,
  },
  {
    id: 'veg-1',
    name: 'Fresh Veggie Depot',
    categoryId: 'vegetables',
    rating: 4.1,
    distanceKm: 1.9,
    etaMinutes: 22,
    isOpenNow: true,
    isVerified: false,
    isTrending: false,
    createdAt: '2025-07-01T09:00:00.000Z',
    isPremium: false,
  },
  {
    id: 'dai-1',
    name: 'Dairy Delight Store',
    categoryId: 'dairy',
    rating: 4.5,
    distanceKm: 3.1,
    etaMinutes: 29,
    isOpenNow: true,
    isVerified: true,
    isTrending: true,
    createdAt: '2025-11-09T09:00:00.000Z',
    isPremium: true,
  },
];
